---
downloads: ~/.ansible-downloads/

configure_dotfiles: true
configure_terminal: false
configure_osx: true

# Set to 'true' to configure the Dock via dockutil.
configure_dock: true
dockitems_remove:
  - Launchpad
  - TV
  - Podcasts
  - 'App Store'
  - Maps
  - Photos
  - Facetime
  - Reminders
  - Freeform
  - TV
  - Music
  - News
dockitems_persist:
  - name: "Firefox"
    path: "/Applications/Firefox.app/"
    pos: 2
  - name: "Google Chrome"
    path: "/Applications/Google Chrome.app/"
    pos: 3
  - name: "Tabby"
    path: "/Applications/Tabby.app/"
    pos: 4
  - name: "1Password"
    path: "/Applications/1Password.app/"
    pos: 5
  - name: "Visual Studio Code"
    path: "/Applications/Visual Studio Code.app/"
    pos: 6
configure_sudoers: true
sudoers_custom_config: |
  # Allow users in admin group to use sudo with no password.
  %admin ALL=(ALL) NOPASSWD: ALL
dotfiles_repo: git@gitlab.com:jonathanmarteen/dotfiles.git
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/Development/GitHub/dotfiles
dotfiles_files:
  - .zshrc
  - .gitignore_global
  - .gitconfig
  - .bash_profile
  - .inputrc
  - .osx
  - .vimrc

homebrew_installed_packages:
  # - ansible # Installed via Pip.
  - autoconf
  - bash-completion
  - docker-completion
  - go
  - gpg
  - k9s
  - direnv
  - awscli
  - aws-iam-authenticator
  - aws-elasticbeanstalk
  - helm
  - kubernetes-cli
  - nmap
  - sqlite
  - nvm
  - nmap
  - packer
  - terraform
  - terraform-docs
  - ssh-copy-id
  - terragrunt
  - vagrant-completion
  - yamllint
  - zsh
  - wget
  - zsh-completions
  - zsh-history-substring-search

homebrew_taps:
  - homebrew/core
  - homebrew/cask

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - firefox
  - google-chrome
  - pritunl
  - slack
  - sourcetree
  - tabby
  - vagrant
  - vagrant-manager
  - virtualbox
  - visual-studio-code
  - 1password
  - spotify
  - docker
  - droplr

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps: []
mas_email: ""
mas_password: ""

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
# - name: drush
#   state: present # present/absent, default: present
#   version: "^8.1" # default: N/A
gem_packages: []
# - name: bundler
#   state: present # present/absent/latest, default: present
#   version: "~> 1.15.1" # default: N/A
npm_packages: []
# - name: webpack
#   state: present # present/absent/latest, default: present
#   version: "^2.6" # default: N/A
pip_packages: []
# - name: mkdocs
#   state: present # present/absent/latest, default: present
#   version: "0.16.3" # default: N/A

# Set to 'true' to configure Sublime Text.
configure_sublime: false
sublime_base_path: '~/Library/Application Support/Sublime Text'
sublime_config_path: "Packages/User"
sublime_package_control: []

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
